---

- name: "Configure the EKS"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"

  roles:
    - project-deployment
    - project-service