---
- name: "Save LoadBalancer's DNS name locally"
  hosts: web
  user: ubuntu
  gather_facts: false
  become: yes
  tasks:
    - name: Get the LoadBalancer's DNS name
      shell: "./bin/kubectl get svc project-service"
      register: elb_url
      args:
        chdir: $HOME

    - name: Copy the output to a local file
      copy:
        content: "{{ elb_url.stdout }}"
        dest: "~/elb_url.txt"
      delegate_to: localhost