apiVersion: v1
kind: Service
metadata:
  name: UdacityDevOps-Capstone-service
spec:
  type: LoadBalancer
  selector:
    app: UdacityDevOps-Capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80