Description: Udacity Devops capstone project, create servers

Parameters:
  EnvironmentName:
    Description: Environtment name using to be prefix for all resources
    Default: devops-capstone
    Type: String
  AMIServerId:
    Description: AMI ID for EC2 instances.
    Type: String
  InstanceType:
    Description: EC2 instance type
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-management-SG
      GroupDescription: Allow port 22 for management
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ServerManagement:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      ImageId: !Ref AMIServerId
      KeyName: devops-capstone
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-management