---
- name: Copy deployment configuration
  copy:
    src: "project-deployment.yaml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "./bin/kubectl apply -f project-deployment.yaml"
  args:
    chdir: $HOME