apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone-deployment
  labels:
    app: devops-capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-capstone-app
  template:
    metadata:
      labels:
        app: devops-capstone-app
    spec:
      containers:
        - name: devops-capstone-app
          image: trinhnt30/devops-capstone
          ports:
            - containerPort: 80