apiVersion: apps/v1
kind: Deployment
metadata:
  name: UdacityDevOps-Capstone-deployment
  labels:
    app: UdacityDevOps-Capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UdacityDevOps-Capstone-app
  template:
    metadata:
      labels:
        app: UdacityDevOps-Capstone-app
    spec:
      containers:
        - name: UdacityDevOps-Capstone-app
          image: trinhnt30/UdacityDevOps-Capstone
          ports:
            - containerPort: 80